title: "Knowledge graph for Single-cell resources"
site_url: https://github.com/Wkt8/sc_resources
plugins:
  - jekyll-remote-theme
remote_theme: "pmarsceill/just-the-docs"

search_enabled: true

mermaid:
  version: "9.1.7"


aux_links:
  "Edit these Docs on GitHub":
    - "https://github.com/Wkt8/sc_resources"
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

markdown: kramdown

# Plugins
tidy_json:
  pretty: true
