title: "Knowledge graph for Single-cell resources"
site_url: https://esapenaventura.github.io/sc_resources
plugins:
  - jekyll-remote-theme
remote_theme: "pmarsceill/just-the-docs"

search_enabled: false

mermaid:
  version: "9.1.7"


aux_links:
  "Edit these Docs on GitHub":
    - "https://github.com/ebi-ait/ingest-programmatic-submissions"
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

markdown: kramdown

# Plugins
tidy_json:
  pretty: true
